- hosts: localhost
  vars:
    vcenter_hostname: "vcsa.vclass.reca6"
    vcenter_username: "S00@vclass.reca6"
    vcenter_password: "VMware1!"
    datacenter_name: "RECA6"
    project_folder: "RECA6/vm/5.Projects/P00"
    
  tasks: 
    - name: Deploy Project - Windows VMs
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'
        
        template: '{{ item.template }}'
        folder: '{{ project_folder }}'
        name: '{{ item.vmname }}'
        esxi_hostname: "{{ item.host }}"
        datastore: "{{ item.datastore }}"
        networks:
        - name: "{{ item.lan }}"
          label: "Network adapter 1"
          connected: True
          start_connected: True
          ip: "{{ item.ip }}"
          netmask: 255.255.255.0
          gateway: "{{ item.gw }}"
          dns_servers: "{{ item.dns }}"
          type: static
        customization:
          hostname: "{{ item.hostname }}"
          autologon: true
          autologoncount: 5
          password: VMware1!
          timezone: 230
        wait_for_customization: yes
        wait_for_customization_timeout: 360
        state: poweredon
      loop:
        - { template: "Temp-WinSvr-02", vmname: "FP-Team2-DNS", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.2", gw: "172.17.1.1", dns: "172.16.1.2", hostname: "DNS" }
      delegate_to: localhost
      register: deploy_vm

    - name: Deploy Project - Linux VMs
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'
        
        template: '{{ item.template }}'
        folder: '{{ project_folder }}'
        name: '{{ item.vmname }}'
        esxi_hostname: "{{ item.host }}"
        datastore: "{{ item.datastore }}"
        networks:
        - name: "{{ item.lan }}"
          label: "Network adapter 1"
          connected: True
          start_connected: True
          ip: "{{ item.ip }}"
          netmask: 255.255.255.0
          gateway: "{{ item.gw }}"
        customization:
          hostname: '{{ item.hostname }}'
          dns_servers:
            - "{{ item.dns }}"
          dns_suffix:
            - "{{ item.domain }}"
        wait_for_customization: yes
        wait_for_customization_timeout: 360
        state: poweredon
      loop:
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-NFS", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.3", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "nfs" }
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-Bastion", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.4", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "bastion" }
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-HAProxy1", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.5", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "haproxy1" }
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-HAProxy2", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.6", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "haproxy2" }
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-Master1", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.11", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "master1" }
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-Master2", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.12", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "master2" }
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-Master3", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.13", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "master3" }
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-Worker1", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.21", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "worker1" }
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-Worker2", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.22", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "worker2" }
        - { template: "Temp-Rocky-02", vmname: "FP-Team2-Worker3", host: "esxi-02.vclass.reca6", datastore: "Local-02", lan: "FP-Team2-K8s", ip: "172.17.1.23", gw: "172.17.1.1", dns: "172.17.1.2", domain: "k8s.private", hostname: "worker3" }
      delegate_to: localhost
      register: deploy_vm
