# NFS 서버 설정
- hosts: nfs
  become: yes
  tasks:
    - name: Install NFS utilities
      dnf:
        name: nfs-utils
        state: present

    - name: Create NFS export directory
      file:
        path: /srv/nfs/k8s
        state: directory
        owner: nobody
        group: nobody
        mode: '0777'

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "/srv/nfs/k8s *(rw,sync,no_subtree_check,no_root_squash)"
        state: present

    - name: Set SELinux boolean for NFS
      command: setsebool -P nfs_export_all_rw 1

    - name: Set SELinux context for NFS export directory
      command: chcon -t nfs_t /srv/nfs/k8s

    - name: Start and enable NFS service
      systemd:
        name: nfs-server
        state: started
        enabled: yes

    - name: Export NFS shares
      command: exportfs -a

# worker 노드에 NFS 마운트
- hosts: worker
  become: yes
  tasks:
    - name: Install NFS utilities
      dnf:
        name: nfs-utils
        state: present

    - name: Create mount point
      file:
        path: /mnt/nfs/k8s
        state: directory

    - name: Mount NFS share
      mount:
        path: /mnt/nfs/k8s
        src: 10.10.10.3:/srv/nfs/k8s
        fstype: nfs
        state: mounted

    - name: Add NFS mount to fstab
      lineinfile:
        path: /etc/fstab
        line: "10.10.10.3:/srv/nfs/k8s /mnt/nfs/k8s nfs defaults 0 0"
        state: present

# master1 노드에 PV 및 PVC 설정
- hosts: master1
  become: yes
  tasks:
    - name: Create PersistentVolume YAML
      copy:
        dest: /home/k8s/nfs-pv.yaml
        content: |
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: nfs-pv
          spec:
            capacity:
              storage: 10Gi
            accessModes:
              - ReadWriteMany
            nfs:
              server: 10.10.10.3
              path: "/srv/nfs/k8s"

    - name: Create PersistentVolumeClaim YAML
      copy:
        dest: /home/k8s/nfs-pvc.yaml
        content: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: nfs-pvc
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 10Gi

    - name: Apply PersistentVolume
      command: kubectl apply -f /home/k8s/nfs-pv.yaml

    - name: Apply PersistentVolumeClaim
      command: kubectl apply -f /home/k8s/nfs-pvc.yaml
