# MongoDB 설치 및 Kubernetes 연동 설정
- hosts: db
  become: yes
  tasks:
    - name: Add MongoDB repository
      copy:
        dest: /etc/yum.repos.d/mongodb.repo
        content: |
          [mongodb-org-5.0]
          name=MongoDZB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/5.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-5.0.asc

    - name: Install MongoDB server
      dnf:
        name: mongodb-server
        state: present
    
    - name: Update MongoDB bindIp to allow external access
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^\\s*bindIp:'
        line: '  bindIp: 0.0.0.0'   # 모든 IP 주소에서 접근 허용
        insertafter: '^net:'       # 'net:' 아래에 추가
        state: present

    - name: Start and enable MongoDB service
      systemd:
        name: mongod
        state: started
        enabled: yes

    - name: Ensure MongoDB is running
      shell: "mongo --eval 'db.runCommand({ ping: 1 })'"
      ignore_errors: yes

# Kubernetes 클러스터에 MongoDB 클라이언트만 설치
- hosts: master1
  become: yes
  tasks:
    - name: Install MongoDB client on Kubernetes node
      dnf:
        name: mongodb-org-shell
        state: present

    - name: Create MongoDB connection script
      copy:
        dest: /home/k8s/mongodb-client.sh
        mode: '0755'
        content: |
          #!/bin/bash
          mongo --host 10.10.10.5 --port 27017 -u root -p VMware1! --authenticationDatabase admin

    - name: Test MongoDB connection from Kubernetes node
      shell: /home/k8s/mongodb-client.sh
      ignore_errors: yes
