---
- hosts: master1
  become: yes
  tasks:
    - name: Update APT repository
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - prometheus
          - grafana
        state: present

    - name: Ensure Prometheus is started and enabled
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Ensure Grafana is started and enabled
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Configure Prometheus
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

    - name: Restart Prometheus to apply new configuration
      systemd:
        name: prometheus
        state: restarted

    - name: Ensure Grafana data directory exists
      file:
        path: /var/lib/grafana
        state: directory
        owner: grafana
        group: grafana

    - name: Add Prometheus as a data source in Grafana
      uri:
        url: "http://localhost:3000/api/datasources"
        method: POST
        user: admin
        password: admin
        headers:
          Content-Type: "application/json"
        body: |
          {
            "name": "Prometheus",
            "type": "prometheus",
            "url": "http://localhost:9090",
            "access": "proxy",
            "basicAuth": false
          }
        status_code: 200
